name: Docker Image CI

on:
  push:
    branches: 
     - master
    paths:
      - .
   
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: aaa # default is 
        # Container registry password
        password: bbb # default is 
        # Container registry server url
        login-server: cccc # default is https://index.docker.io/v1/
    
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        docker push my-image-name:$(date +%s)
    
    # Connect server sample 
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        # Command to execute on the remote server.
        command: ls -a
        # Hostname or IP address of the server.
        host: ip_address # optional, default is localhost
        # Username for authentication.
        username: user_name # optional
        # Port number of the server.
        port: 22 # optional, default is 22
        # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        #privateKey: # optional
        # Password for password-based user authentication.
        password: password # optional
        # For an encrypted private key, this is the passphrase used to decrypt it.
        # passphrase: # optional
        # Try keyboard-interactive user authentication if primary user authentication method fails.
        #tryKeyboard: # optional
